name = "ReactionNetworkImporters"
uuid = "b4db0fb7-de2a-5028-82bf-5021f5cfa881"
authors = ["Samuel Isaacson <isaacsas@users.noreply.github.com>"]
version = "0.15.0"

[deps]
Catalyst = "479239e8-5488-4da2-87a7-35f2df7eef83"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"

[compat]
Aqua = "0.8"
CSVFiles = "1"
Catalyst = "14"
DataFrames = "1.3"
DataStructures = "0.18.13"
DiffEqBase = "6.151"
LinearAlgebra = "1.10"
ModelingToolkit = "9.24"
OrdinaryDiffEq = "6.8"
SafeTestsets = "0.1"
SparseArrays = "1.10"
Sundials = "4.4"
Symbolics = "5.33"
Test = "1"
julia = "1.10"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
CSVFiles = "5d742f6a-9f54-50ce-8119-2520741973ca"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DiffEqBase = "2b5f629d-d688-5b77-993f-72d75c75574e"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
Sundials = "c3572dad-4567-51f8-b174-8c6c989267f4"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"

[targets]
test = ["Aqua", "CSVFiles", "DataFrames", "DiffEqBase", "LinearAlgebra", "OrdinaryDiffEq", "SafeTestsets", "Sundials", "Test"]
